Repository Normation/rudder-packages, pull requests merged in 2018-02, with the labels that each got.

#1503 Fixes #10498: Stopping slapd fails if pid file is empty
  rudder-inventory-ldap/SOURCES/rudder-inventory-ldap.init
Labels: Ready for merge, qa: Can't merge

#1501 Fixes #6758: rudder-webapp upgrade doesn't commit updates to ncf hooks
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/postinst
Labels: Ready for merge, qa: Can't merge

#1505 Fixes #12116: rudder-webapp upgrade doesn't commit updates to ncf hooks
  rudder-webapp/debian/postinst
Labels: Ready for merge, qa: Can't merge

#1511 Fixes #12132: Missing depedency to use rudder-slapd on rpm systems
  rudder-inventory-ldap/SPECS/rudder-inventory-ldap.spec
Labels: qa: Can't merge

#1512 Fixes #8969: remove ld.so.conf
  rudder-agent/SOURCES/Makefile
  rudder-agent/SOURCES/rudder-agent-postinst
  rudder-agent/SOURCES/rudder.conf
  rudder-agent/SPECS/rudder-agent.spec
  rudder-agent/debian/dirs
  rudder-inventory-ldap/SOURCES/rudder-inventory-ldap.conf
  rudder-inventory-ldap/SPECS/rudder-inventory-ldap.spec
  rudder-inventory-ldap/debian/postinst
  rudder-inventory-ldap/debian/rules
Labels: Ready for merge
