Repository Normation/rudder-packages, pull requests merged in 2018-08, with the labels that each got.

#1641 Fixes #13172: Download sources from repository.rudder.io instead of www.normation.com
  ncf-api-virtualenv/SOURCES/Makefile
  packages.makefile
  rudder-agent/SOURCES/Makefile
  rudder-inventory-endpoint/SOURCES/Makefile
  rudder-inventory-ldap/SOURCES/Makefile
  rudder-jetty/SOURCES/Makefile
  rudder-server-relay/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: qa: Can't merge

#1643 Fixes #13198: Fix bdb download link from repository.rudder.io
  rudder-inventory-ldap/SOURCES/Makefile
Labels: qa: Can't merge

#1650 Fixes #13295: Add sles 15 support to rudder-packages
  ncf-api-virtualenv/SOURCES/.dependencies
  rudder-agent/SOURCES/.dependencies
  rudder-inventory-ldap/SOURCES/.dependencies
  rudder-server-relay/SOURCES/.dependencies
  rudder-techniques/SOURCES/.dependencies
Labels: Ready for merge, qa: Can't merge

#1652 Fixes #12856: Use CFEngine 3.12 in Rudder agent
  rudder-agent/SOURCES/Makefile
  rudder-agent/SOURCES/patches/cfengine/12130-avoid-copy-variable-table.patch
  rudder-agent/SOURCES/patches/cfengine/12241-key-option-cf-key.patch
  rudder-agent/SOURCES/patches/cfengine/12243-do-not-reload-failsafe.patch
  rudder-agent/SOURCES/patches/cfengine/12397-fix-acl-detection-configure.patch
Labels: Ready for merge

#1653 Fixes #13310: Disable inclusion of openssl/engine.h
  rudder-agent/SOURCES/patches/cfengine/13310-disable-openssl-engine.patch
Labels: Ready for merge

#1654 Fixes #13311: Broken agent build on linux platforms
  rudder-agent/SOURCES/patches/cfengine/13311-test-wifcontinue-existence.patch
Labels: Ready for merge

#1655 Fixes #13314: Update agent dependencies
  ncf-api-virtualenv/SOURCES/Makefile
  ncf/SOURCES/Makefile
  rudder-agent/SOURCES/Makefile
  rudder-inventory-endpoint/SOURCES/Makefile
  rudder-inventory-ldap/SOURCES/Makefile
  rudder-inventory-ldap/SOURCES/patches/openldap/0002-dn2id-modrdn-idlcache-sub.patch
  rudder-reports/SOURCES/Makefile
  rudder-server-relay/SOURCES/Makefile
  rudder-server-root/SOURCES/Makefile
  rudder-techniques/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#1656 Fixes #13316: Upgrade openssl
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge, qa: Can't merge

#1657 Fixes #13315: Remove support for old system on rudder server builds
  ncf-api-virtualenv/SOURCES/Makefile
  ncf-api-virtualenv/SPECS/ncf-api-virtualenv.spec
  ncf-api-virtualenv/debian/control
  rsyslog-suse/BUILD/.placeholder
  rsyslog-suse/RPMS/.placeholder
  rsyslog-suse/SOURCES/.dependencies
  rsyslog-suse/SOURCES/Makefile
  rsyslog-suse/SOURCES/rsyslog-4.8.0.tar.bz2
  rsyslog-suse/SOURCES/rsyslog.conf.in
  rsyslog-suse/SOURCES/rsyslog.d.remote.conf.in
  rsyslog-suse/SOURCES/rsyslog.early.conf.in
  rsyslog-suse/SOURCES/rsyslog.sysconfig
  rsyslog-suse/SOURCES/rsyslogd.init
  rsyslog-suse/SPECS/rsyslog.spec
  rsyslog-suse/SRPMS/.placeholder
  rudder-inventory-endpoint/SPECS/rudder-inventory-endpoint.spec
  rudder-inventory-endpoint/debian/control
  rudder-inventory-endpoint/debian/postinst
  rudder-inventory-ldap/SPECS/rudder-inventory-ldap.spec
  rudder-inventory-ldap/debian/control
  rudder-inventory-ldap/debian/postinst
  rudder-jetty/SPECS/rudder-jetty.spec
  rudder-reports/SPECS/rudder-reports.spec
  rudder-server-relay/SOURCES/Makefile
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
  rudder-webapp/debian/rules
Labels: Ready for merge

#1658 Fixes #13320: keep only systemd on server packages
  ncf-api-virtualenv/SPECS/ncf-api-virtualenv.spec
  ncf-api-virtualenv/debian/postinst
  rudder-inventory-ldap/SPECS/rudder-inventory-ldap.spec
  rudder-inventory-ldap/debian/control
  rudder-inventory-ldap/debian/postinst
  rudder-jetty/SPECS/rudder-jetty.spec
  rudder-jetty/debian/control
  rudder-jetty/debian/postinst
  rudder-reports/SPECS/rudder-reports.spec
  rudder-reports/debian/control
  rudder-reports/debian/postinst
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
  rudder-server-relay/debian/postinst
  rudder-server-root/SOURCES/rudder-server-root-postinst
  rudder-server-root/SOURCES/rudder-server.init
  rudder-server-root/debian/control
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/postinst
Labels: Ready for merge

#1659 Fixes #13323: Upgrade jetty to 9.4.11
  rudder-agent/SOURCES/Makefile
  rudder-inventory-ldap/SOURCES/Makefile
  rudder-jetty/SOURCES/Makefile
  rudder-server-root/SOURCES/Makefile
Labels: Ready for merge

#1661 Fixes #13325: Remove apache 2.2 support
  ncf-api-virtualenv/SOURCES/ncf-api-virtualenv.conf
  rudder-server-relay/SOURCES/rudder-apache-relay-common.conf
  rudder-server-relay/SOURCES/rudder-apache-relay-ssl.conf
  rudder-server-relay/SOURCES/rudder-networks-policy-server.conf
  rudder-server-relay/SOURCES/rudder-networks.conf
  rudder-server-relay/SOURCES/rudder-vhost.conf
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/conffiles
  rudder-server-relay/debian/rules
  rudder-webapp/SOURCES/rudder-apache-webapp-common.conf
  rudder-webapp/SOURCES/rudder-apache-webapp-ssl.conf
Labels: Ready for merge

#1662 Fixes #13328: Upgrade jetty to 9.4.11
  rudder-jetty/SOURCES/patches/jetty/jetty-init-sizecheck.patch
Labels: Ready for merge

#1651 Fixes #13300: parallel build on rpmbuild hides build error
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge, qa: Can't merge

#1664 Fixes #13336: Upgrade jetty to 9.4.11
  rudder-jetty/SOURCES/patches/jetty/jetty-init-redirect-stderrout.patch
Labels: Ready for merge

#1666 Fixes #13338: Missing local path in parent issue
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#1663 Fixes #13329: Use correct version when building Slackware packages
  packages.makefile
  rudder-agent/slackware/rudder-agent.SlackBuild
Labels: Ready for merge

#1667 Fixes #13339: libxml fails to build with old compiler
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#1668 Fixes #13363: libxml 2.9.8 doesn't compile on aix
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#1669 Fixes #13371: Upgrade python related dependencies
  ncf-api-virtualenv/SOURCES/Makefile
  rudder-server-relay/SOURCES/Makefile
  rudder-server-relay/SOURCES/relay-api/requirements.txt
Labels: Ready for merge
