Repository Normation/rudder-packages, pull requests merged in 2018-07, with the labels that each got.

#1611 Fixes #12930: During an upgrade of Rudder, if a new generic method appears in ncf, that is also on local method, all is broken
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge, qa: Can't merge

#1610 Fixes #12331: rudder-pkg must disable plugin during major version Rudder update
  rudder-server-relay/SOURCES/rudder-pkg
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge

#1612 Fixes #12933: Improve parent ticket code
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge, qa: Can't merge

#1613 Fixes #12903: Build error on AIX, empty list of man page to compress
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#1615 Fixes #12954: Previous fix does not work
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge, qa: Can't merge

#1616 Fixes #12956: Parent ticket does not solve the issue with broken policy generation
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge

#1618 Fixes #12966: Can not install rudder agent on AIX: libyaml.a could not be loaded
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge

#1620 Fixes #12976: Parent fix is not applied to the right place
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge

#1619 Fixes #12973: Accept external options to rpmbuild calls
  packages.makefile
Labels: Ready for merge

#1622 Fixes #12984: Parent fix does not work, we need to use a parameter
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge

#1623 Fixes #12991: Parent fix breaks rpm builds
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge

#1625 Fixes #13005: echo -n doewn't work on aix
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: qa: Can't merge

#1627 Fixes #10646: Error at the end of generation after accepting 500 nodes
  rudder-inventory-ldap/SOURCES/rudder-inventory-ldap.default
  rudder-inventory-ldap/SOURCES/rudder-slapd-configure
  rudder-inventory-ldap/SOURCES/slapd.conf
Labels: qa: Can't merge

#1635 Fixes #13070: Add the slackware target to packages.makefile
  packages.makefile
Labels: qa: Can't merge

#1629 Fixes #13041: rudder-metrics-reporting fail to report reports on directive/expected reports in 4.3, as the database schema changed
  rudder-webapp/SOURCES/rudder-metrics-reporting
Labels: qa: Can't merge
