Repository Normation/rudder-packages, pull requests merged in 2019-10, with the labels that each got.

#2096 Fixes #15815: Build rudder-api-client for 5.0
  rudder-api-client/Makefile
  rudder-api-client/SOURCES/.dependencies
  rudder-api-client/SOURCES/.placeholder
  rudder-api-client/SPECS/rudder-api-client.spec
  rudder-api-client/debian/changelog
  rudder-api-client/debian/compat
  rudder-api-client/debian/control
  rudder-api-client/debian/copyright
  rudder-api-client/debian/rules
Labels: qa: Can't merge

#2099 Fixes #15829: Cleanup roles in packaging
  rudder-webapp/SOURCES/rudder-init
  rudder-webapp/SOURCES/rudder-node-to-relay
  rudder-webapp/SOURCES/rudder-upgrade
Labels: qa: Can't merge

#2100 Fixes #13866: Invalid json in Rudder inventory hooks fails to log the problem
  rudder-agent/SOURCES/patches/fusioninventory/11726-Extend-Rudder-specific-inventory-with-clie.patch
Labels: qa: Can't merge

#2102 Fixes #15853: Missing rudder-api-client folder in rudder-packages
  rudder-api-client/Makefile
  rudder-api-client/SOURCES/.dependencies
  rudder-api-client/SOURCES/.placeholder
  rudder-api-client/SPECS/rudder-api-client.spec
  rudder-api-client/debian/changelog
  rudder-api-client/debian/compat
  rudder-api-client/debian/control
  rudder-api-client/debian/copyright
  rudder-api-client/debian/rules
Labels: qa: Can't merge

#2104 Fixes #15859: Missing makefile in rudder-packages for rudder-api-client
  rudder-api-client/SOURCES/Makefile
Labels: Ready for merge

#2106 Fixes #15865: curl doesnt fail on 404 during packaging
  rudder-agent/SOURCES/Makefile
  rudder-api-client/SOURCES/Makefile
  rudder-reports/SOURCES/Makefile
  rudder-server-root/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#2101 Fixes #15765: Merge inventory endpoint configuration file into rudder-web.properties
  rudder-webapp/SOURCES/rudder-jetty.conf
  rudder-webapp/SOURCES/rudder-upgrade
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge, qa: Can't merge

#2109 Fixes #15879: ldap build should not use --debug
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#2111 Fixes #15886: Caching depends on python
  build-caching
Labels: Ready for merge

#2112 Fixes #15892: Caching depends on python
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
Labels: Ready for merge

#2113 Fixes #15895: Caching depends on python
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
Labels: Ready for merge

#2114 Fixes #15898: Caching depends on python
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#2115 Fixes #15900: /opt/rudder/bin/rudder-keys reset-status need a pubkey
  rudder-webapp/SOURCES/rudder-keys
Labels: Ready for merge, qa: Can't merge

#2118 Fixes #15914: On sles12 the webapp is in access denied after fresh install
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: Ready for merge, qa: Can't merge

#2117 Fixes #15911: build-caching cache the same thing twice
  build-caching
Labels: Ready for merge

#2120 Fixes #15924: ldap build should not use --debug
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#2110 Fixes #15881: cache may ignore some change within dependencies patches
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2105 Fixes #15861: Remove rudder-api-client/SOURCES/Makefile in 6.0
  rudder-api-client/SOURCES/Makefile
Labels: qa: Can't merge

#2122 Fixes #15979: Unwanted systemctl output in rudder-reports postinst
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge

#2123 Fixes #15985: Remove debug pprint from rudder-pkg
  rudder-server-relay/SOURCES/rudder-pkg
Labels: qa: Can't merge

#2124 Fixes #15937: Postinst of rudder-agent on centos6 tries to use systemd
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: Ready for merge

#2127 Fixes #16057: Packaging files for rudder-api-client in 5.0 are not correct
  rudder-api-client/SOURCES/.dependencies
  rudder-api-client/debian/rules
Labels: qa: Can't merge

#2128 Fixes #16061: Debian build of rudder-api-client fails due to already existing BUILD folder
  rudder-api-client/debian/rules
Labels: qa: Can't merge

#2129 Fixes #16062: Rudder-api-client build is running two times the build part
  rudder-api-client/debian/rules
Labels: qa: Can't merge

#2130 Fixes #16085: rudder-api-client packaging untar the sources two times
  rudder-api-client/SOURCES/Makefile
  rudder-api-client/debian/rules
Labels: Ready for merge, qa: Can't merge

#2131 Fixes #16088: Rudder-api-client fails to build, debian packaging files are not copied properly by dh
  rudder-api-client/debian/rules
Labels: Ready for merge, qa: Can't merge
