Repository Normation/rudder-packages, pull requests merged in 2019-09, with the labels that each got.

#2052 Fixes #15643: Remove the User techniques category from postinstall
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge

#2045 Fixes #14822: Remove warning: "Nashorn engine is planned to be removed from a future JDK release "
  rudder-jetty/SOURCES/rudder-jetty.conf
Labels: qa: Can't merge

#2054 Fixes #15650: Remove relay-api from packaging
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/postinst
  rudder-webapp/SOURCES/rudder-apache-webapp-common.conf
Labels: Ready for merge, qa: Can't merge

#2053 Fixes #15649: At installation Rudder-webapp only creates rudder-slapd and ncf-api-venv users but do not force group creation
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge, qa: Can't merge

#2055 Fixes #15652: Too many quotes in nashorn warning JDK parameter
  rudder-jetty/SOURCES/rudder-jetty.conf
Labels: qa: Can't merge

#2051 Fixes #15624: Missing SOURCES directory in rudder-packages/rudder-api-client
  rudder-api-client/SOURCES/.placeholder
  rudder-api-client/SPECS/rudder-api-client.spec
  rudder-api-client/debian/copyright
Labels: qa: Can't merge

#2056 Fixes #15653: Missing migration script for vacuum change
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/rules
Labels: qa: Can't merge

#2057 Fixes #15659: Webapp fails to generate policies due to java nashorn warning setting
  rudder-jetty/SOURCES/rudder-jetty.conf
Labels: qa: Can't merge

#2058 Fixes #15662: Perl dependency in the agent package is not in dependencies directory
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2059 Fixes #15663: Perl dependency in the agent package is not in dependencies directory
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2063 Fixes #10623: Hooks content/permissions are changed during Rudder upgrade (for ex /opt/rudder/etc/hooks.d/policy-generation-node-ready/10-cf-promise-check is replaced)
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
  rudder-webapp/debian/postinst
  rudder-webapp/debian/preinst
Labels: qa: Can't merge

#2066 Fixes #15687: Hooks content/permissions are changed during Rudder upgrade (for ex /opt/rudder/etc/hooks.d/policy-generation-node-ready/10-cf-promise-check is replaced)
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/postinst
Labels: qa: Can't merge

#2067 Fixes #15690: mod_proxy is not enabled in a relay
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/postinst
Labels: Ready for merge

#2072 Fixes #15703: Prerm does not backup ppkeys
  rudder-agent/SOURCES/rudder-agent-postinst
  rudder-agent/SPECS/rudder-agent.spec
Labels: qa: Can't merge

#2074 Fixes #15711: Rudder api client expect python3 which is not available by default on rhel7
  rudder-api-client/SPECS/dependencies
  rudder-api-client/SPECS/rudder-api-client.spec
Labels: qa: Can't merge

#2076 Fixes #15720: Wrong python version used in rudder-server-relay build
  rudder-api-client/SPECS/rudder-api-client.spec
  rudder-server-relay/SPECS/dependencies
  rudder-server-relay/SPECS/rudder-server-relay.spec
Labels: qa: Can't merge

#2084 Fixes #15737: packages fail to build on rpm
  rudder-agent/slackware/rudder-agent.SlackBuild
  rudder-server-relay/SPECS/rudder-server-relay.spec
Labels: qa: Can't merge

#2083 Fixes #15736: Agent fail to build on slackware 14.1
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2085 Fixes #15753: Apache modules needed by rudder-webapp are listed in a file which is not included in the apache conf file
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: qa: Can't merge

#2086 Fixes #15754: rhel5 fails to get sources
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2087 Fixes #15758: Add -XX:+UseStringDeduplication in G1GC optionnal config
  rudder-jetty/SOURCES/rudder-jetty.default
Labels: qa: Can't merge

#2088 Fixes #15763: Create /opt/rudder/etc/plugins/licenses at server install
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/dirs
Labels: qa: Can't merge

#2092 Fixes #15788: Remove curl option http 1.1
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2091 Fixes #15787: Better realclean of sources in rudder-agent makefile
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge
