Repository Normation/rudder-packages, pull requests merged in 2019-04, with the labels that each got.

#1837 Fixes #14564: Remove compiler optimization on aix for debugging
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#1840 Fixes #14576: Remove debug data from aix binaries
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#1847 Fixes #14608: debian8 cannot install jdk from backports anymore
  rudder-inventory-endpoint/debian/rules
  rudder-webapp/debian/rules
Labels: qa: Can't merge

#1848 Fixes #14610: debian8 cannot install jdk from backports anymore
  rudder-inventory-endpoint/debian/rules
  rudder-webapp/debian/rules
Labels: Ready for merge

#1849 Fixes #14614: debian8 cannot install jdk from backports anymore
  rudder-inventory-endpoint/debian/rules
  rudder-webapp/debian/rules
Labels: Ready for merge

#1852 Fixes #14644: When installing rudder-agent, there's a long wait at the end of the install because of #14258
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: Ready for merge, qa: Can't merge

#1853 Fixes #14659: Remove version replacement in packages and cleanup RUDDER_VERSION_TO_PACKAGE
  ncf-api-virtualenv/SOURCES/Makefile
  ncf/SOURCES/Makefile
  rudder-agent/SOURCES/Makefile
  rudder-agent/solaris/Makefile
  rudder-inventory-endpoint/SOURCES/Makefile
  rudder-inventory-ldap/SOURCES/Makefile
  rudder-reports/SOURCES/Makefile
  rudder-server-relay/SOURCES/Makefile
  rudder-server-root/SOURCES/Makefile
  rudder-techniques/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: qa: Can't merge

#1855 Fixes #14661: Remove relay sources from rudder-packages
  qa-test
  rudder-server-relay/SOURCES/Makefile
  rudder-server-relay/SOURCES/docopt.py
  rudder-server-relay/SOURCES/openssl.cnf
  rudder-server-relay/SOURCES/relay-api/.gitignore
  rudder-server-relay/SOURCES/relay-api/README
  rudder-server-relay/SOURCES/relay-api/apache/relay-api.wsgi
  rudder-server-relay/SOURCES/relay-api/cleanup.sh
  rudder-server-relay/SOURCES/relay-api/nodeslist.json.example
  rudder-server-relay/SOURCES/relay-api/relay_api/__init__.py
  rudder-server-relay/SOURCES/relay-api/relay_api/common.py
  rudder-server-relay/SOURCES/relay-api/relay_api/remote_run.py
  rudder-server-relay/SOURCES/relay-api/relay_api/shared_files.py
  rudder-server-relay/SOURCES/relay-api/relay_api/views.py
  rudder-server-relay/SOURCES/relay-api/requirements.txt
  rudder-server-relay/SOURCES/relay-api/run.py
  rudder-server-relay/SOURCES/rudder-apache-relay-common.conf
  rudder-server-relay/SOURCES/rudder-apache-relay-nossl.conf
  rudder-server-relay/SOURCES/rudder-apache-relay-ssl.conf
  rudder-server-relay/SOURCES/rudder-networks-24.conf
  rudder-server-relay/SOURCES/rudder-networks-policy-server-24.conf
  rudder-server-relay/SOURCES/rudder-pkg
  rudder-server-relay/SOURCES/rudder-relay-apache
  rudder-server-relay/SOURCES/rudder-relay.cron
  rudder-server-relay/SOURCES/rudder-relay.fc
  rudder-server-relay/SOURCES/rudder-relay.sudo
  rudder-server-relay/SOURCES/rudder-relay.te
  rudder-server-relay/SOURCES/rudder-vhost.conf
  rudder-server-relay/SOURCES/ssl/ca.cert
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/changelog
  rudder-server-relay/debian/control
  rudder-server-relay/debian/copyright
  rudder-server-relay/debian/rules
Labels: qa: Can't merge

#1861 Fixes #14678: Add new dependencies to package relay
  rudder-server-relay/SOURCES/.dependencies
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
Labels: qa: Can't merge

#1869 Fixes #14701: Remove asciidoc dependencies from relay package
  rudder-server-relay/SOURCES/.dependencies
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
Labels: qa: Can't merge

#1873 Fixes #6403: Postgresql misconfigured when not the default distrib package (ex: Centos 6 with Postgresql 9.3 from pgfoundry.org)
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge

#1877 Fixes #14754: debian 8 packages fail to build
  rudder-inventory-endpoint/debian/rules
  rudder-inventory-endpoint/debian/webupd8team.key
  rudder-webapp/debian/rules
  rudder-webapp/debian/webupd8team.key
Labels: qa: Can't merge

#1878 Fixes #14759: debian server 5.1 packages won't build
  ncf/SOURCES/Makefile
  rudder-ldap/Makefile
  rudder-ldap/debian/rules
  rudder-reports/Makefile
  rudder-reports/debian/rules
  rudder-server-relay/Makefile
  rudder-server-relay/debian/rules
  rudder-server-root/Makefile
  rudder-server-root/debian/rules
  rudder-webapp/Makefile
  rudder-webapp/debian/rules
Labels: qa: Can't merge

#1882 Fixes #14765: debian 8 server fail to install jdk during build
  rudder-inventory-endpoint/debian/rules
  rudder-webapp/debian/rules
Labels: qa: Can't merge

#1887 Fixes #14777: Packaging fails at test step
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#1888 Fixes #8901: beautify pg_hba.conf
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge
