Repository Normation/rudder-packages, pull requests merged in 2019-05, with the labels that each got.

#1891 Fixes #11126: ncf-api-virtualenv does not have a group created
  ncf-api-virtualenv/SPECS/ncf-api-virtualenv.spec
Labels: Ready for merge, qa: Can't merge

#1893 Fixes #14827: Error when upgrading to Rudder 5.0.10 using centos7 with custom postgresql
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge

#1894 Fixes #14829: Error in parent ticket - missing Digest/SHA.pm as a dependency on centos
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: qa: Can't merge

#1895 Fixes #14832: postgresql is not started properly at postinstall on sles12
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge

#1899 Fixes #14839: Use rudder agent check at postinst
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: qa: Can't merge

#1901 Fixes #14846: error message in logs during install on postgresql detection
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge

#1904 Fixes #14848: parent itcket broek postgresql identification
  rudder-reports/SPECS/rudder-reports.spec
Labels: qa: Can't merge

#1900 Fixes #14819: Add openssl configuration to agent package
  rudder-agent/SOURCES/Makefile
  rudder-agent/SOURCES/openssl.cnf
Labels: qa: Can't merge

#1913 Fixes #14893: RHE7 and SLES12 don't have mod wsgi for python 3
  rudder-server-relay/SPECS/dependencies
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
  rudder-webapp/SPECS/dependencies
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
Labels: qa: Can't merge

#1921 Fixes #14905: Move away from python 2 to python 3 in relay-api
  rudder-server-relay/SPECS/dependencies
  rudder-webapp/SPECS/dependencies
Labels: Ready for merge

#1924 Fixes #14914: rudder agent dependencies are missing for rhel8
  ncf-api-virtualenv/SOURCES/.dependencies
  rudder-agent/SOURCES/.dependencies
  rudder-inventory-endpoint/SOURCES/.dependencies
  rudder-inventory-ldap/SOURCES/.dependencies
  rudder-server-relay/SOURCES/.dependencies
  rudder-webapp/SOURCES/.dependencies
Labels: qa: Can't merge

#1908 Fixes #14872: Deduplicate cfengine binaries
  rudder-agent/SOURCES/Makefile
  rudder-agent/SOURCES/rudder-agent-postinst
  rudder-agent/SOURCES/rudder-agent.sh
  rudder-agent/SPECS/rudder-agent.spec
  rudder-agent/debian/dirs
  rudder-agent/debian/postinst
  rudder-agent/debian/preinst
  rudder-agent/debian/prerm
  rudder-agent/solaris/Makefile
  rudder-agent/solaris/Prototype.base
  rudder-agent/solaris/checkinstall
  rudder-agent/solaris/pkginfo
  rudder-agent/solaris/postinstall
  rudder-agent/solaris/postremove
  rudder-agent/solaris/preremove
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/postinst
  rudder-server-root/debian/postinst
  rudder-webapp/debian/postinst
Labels: Ready for merge, qa: Can't merge

#1928 Fixes #14933: Update embedded openssl version
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#1927 Fixes #14921: Update CFEngine to 3.12.2
  rudder-agent/SOURCES/Makefile
  rudder-agent/SOURCES/patches/cfengine/12243-do-not-reload-failsafe.patch
Labels: qa: Can't merge

#1932 Fixes #14956: Cleanup caching in 5.0
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#1933 Fixes #14957: Build dependencies in a single directory
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#1934 Fixes #14958: Disable shebange mangling in rhel8
  rudder-agent/SPECS/rudder-agent.spec
Labels: qa: Can't merge

#1935 Fixes #14955: Better caching for builds
  build-caching
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#1942 Fixes #14973: Remove maven dependency at package time
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/mvn-like
  rudder-webapp/SOURCES/settings-external.xml.tpl
  rudder-webapp/SPECS/dependencies
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
Labels: qa: Can't merge

#1949 Fixes #14999: Cache cfengine builds
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge
