Repository Normation/rudder-packages, pull requests merged in 2020-05, with the labels that each got.

#2268 Fixes #17337: Package cache is updated at each run
  rudder-agent/SOURCES/patches/cfengine/17337-force-lock-on-package-db
Labels: qa: Can't merge

#2269 Fixes #17339: rudder fails to build in 6.0
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2274 Fixes #17215: create migration script for LDAP indexes
  rudder-webapp/SOURCES/rudder-upgrade
Labels: qa: Can't merge

#2277 Fixes #17360: rpm build logs are huge
  rudder-agent/SPECS/rudder-agent.spec
Labels: qa: Can't merge

#2283 Fixes #17371: cf-agent writes a lot of times to performance db
  rudder-agent/SOURCES/patches/cfengine/17335-remove-preformance-writes.patch
Labels: Ready for merge

#2275 Fixes #17356: Missing dependency on iproute2
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
Labels: qa: Can't merge

#2287 Fixes #17395: SELinux policy for technique editor is not applied anymore after upgrade on RHEL/Centos server
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: Ready for merge

#2288 Fixes #17397: Error while upgrading rudder from 6.0.5 to 6.1 nightly on debian
  rudder-webapp/debian/postinst
Labels: Ready for merge

#2289 Fixes #17402: Missing dependencies between server services
  rudder-webapp/SOURCES/rudder-jetty.service
Labels: Ready for merge

#2285 Fixes #17380: Debug script is broken in 6.0
  rudder-agent/SOURCES/debug-script/lib/collect
  rudder-agent/SOURCES/debug-script/tests/cfengine_server_connection_agent
  rudder-agent/SOURCES/debug-script/tests/rudder_api
  rudder-agent/SOURCES/debug-script/tests/rudder_cf_serverd_logs
  rudder-agent/SOURCES/debug-script/tests/rudder_get_server_uuid_agent
  rudder-agent/SOURCES/debug-script/tests/rudder_packages_agent
  rudder-agent/SOURCES/debug-script/tests/rudder_unsent_inventories_agent
  rudder-agent/SOURCES/debug-script/tests/rudder_venv_user_git_access
Labels: Ready for merge

#2286 Fixes #17386: We use the "service" command (on CentOS7) but do not not depend on the package providing it
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge

#2291 Fixes #17433: Python scripts on rhel7 are set to use python3 which is not available
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: Ready for merge

#2267 Fixes #17336: cf-agent writes a lot of times to cf_lock db
  rudder-agent/SOURCES/17336-remove-lock-db-backup.patch
Labels: Ready for merge, qa: Can't merge

#2273 Fixes #17345: add rudder-synchonize within Rudder
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/rudder_synchronize.py
Labels: qa: Can't merge

#2294 Fixes #17495: apache acl are empty after installation
  rudder-webapp/SOURCES/rudder-init
Labels: qa: Can't merge

#2297 Fixes #17532: when upgrading to 6.1, ldap indexing should be normal and not quick
  rudder-webapp/SOURCES/rudder-upgrade
Labels: qa: Can't merge

#2302 Fixes #17564: apache acl are still empty after installation
  rudder-webapp/SOURCES/rudder-init
Labels: Ready for merge

#2303 Fixes #17565: Apache reload error during root server setup
  rudder-webapp/SOURCES/rudder-init
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: qa: Can't merge
