Repository Normation/rudder-packages, pull requests merged in 2020-04, with the labels that each got.

#2224 Fixes #17012: remove rudder-plugin script from makefile
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: qa: Can't merge

#2229 Fixes #17055: Add systemd hardening config for slapd
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/rudder-slapd-hardening
Labels: qa: Can't merge

#2235 Fixes #17139: add jq to rudder agent
  rudder-agent/SOURCES/Makefile
  rudder-agent/SPECS/rudder-agent.spec
  rudder-agent/debian/rules
  rudder-agent/slackware/rudder-agent.SlackBuild
  rudder-agent/solaris/packaging.sh
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge, qa: Can't merge

#2240 Fixes #17169: jq fails to build on old distro
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#2241 Fixes #17171: jq fails to build on old distro
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#2242 Fixes #17175: package fails to build jq
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#2239 Fixes #17166: Remove packaging of ncf api
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/ncf-api-virtualenv.conf
  rudder-webapp/SOURCES/ncf-api-virtualenv.fc
  rudder-webapp/SOURCES/ncf-api-virtualenv.te
  rudder-webapp/SOURCES/ncf_api_flask_app.wsgi
  rudder-webapp/SOURCES/rudder-apache-webapp-ssl.conf
  rudder-webapp/SOURCES/rudder-webapp-postinst
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
  rudder-webapp/debian/links
  rudder-webapp/debian/postinst
Labels: Ready for merge, qa: Can't merge

#2244 Fixes #17185: Parent broke apache syntax
  rudder-webapp/SOURCES/rudder-apache-webapp-ssl.conf
Labels: Ready for merge

#2246 Fixes #17187: rudderlang makefile integration
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge, qa: Can't merge

#2247 Fixes #17197: ncf api file is still packaged, breaking builds
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge

#2248 Fixes #17198: We need to stop apache before removing ncf-api-venv user
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge

#2243 Fixes #17178: Update embedded openssl version to 1.1.1g
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge

#2208 Fixes #16790: Our agent package contains CFEngine systemd units
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2251 Fixes #17217: Replace node-to-relay script from rudder-package
  rudder-webapp/SOURCES/rudder-node-to-relay
Labels: qa: Can't merge

#2259 Fixes #17262: openssl fails to build on aix
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge
