Repository Normation/rudder-packages, pull requests merged in 2020-10, with the labels that each got.

#2367 Fixes #18291:
  rudder-agent/SOURCES/patches/cfengine/18286-add-copyfrom-restrict-keys-keyword.patch
Labels: Trigger test

#2368 Fixes #17878: All plugins are disabled after a minor upgrade
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge, qa: Can't merge

#2372 Fixes #18392: Update dependencies for Rudder
  rudder-agent/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test, qa: Can't merge

#2357 Fixes #18111: create migration script to remove index on keyvalue
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge

#2374 Fixes #18404: systemctl restart rudder-server does nothing
  rudder-webapp/SOURCES/rudder-jetty.service
  rudder-webapp/SOURCES/rudder-slapd.service
Labels: Ready for merge

#2376 Fixes #18435: Version rudder-api-client like Rudder
  rudder-api-client/SPECS/rudder-api-client.spec
Labels: Ready for merge

#2378 Fixes #18445: revert parent changes on openldap to use again 2.4.47
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge
