Repository Normation/rudder-packages, pull requests merged in 2020-06, with the labels that each got.

#2299 Fixes #17536: Change all python3 scripts to python2 on rhel7 at build time
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge, qa: Can't merge

#2307 Fixes #17591: The webapp is unable to start after a fresh install
  rudder-reports/SOURCES/rudder-reports-postinst
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
Labels: Ready for merge, qa: Can't merge

#2309 Fixes #17607: Parent fix give an error log in the output
  rudder-reports/SOURCES/rudder-reports-postinst
Labels: Ready for merge

#2308 Fixes #17606: Agent uses "cmp" command but it is not a dependency
  rudder-agent/SPECS/rudder-agent.spec
  rudder-agent/debian/control
Labels: Ready for merge

#2312 Fixes #17659: An error in during upgrade to 6.1 breaks rudder upgrade and everything
  rudder-webapp/SOURCES/rudder-webapp-postinst
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: Ready for merge

#2313 Fixes #17681: Upgrade to 6.1 fails on httpd start beacause of old ncf conf is still present on rpm
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: qa: Can't merge

#2318 Fixes #17717: systemd detection fails when init has parameters
  rudder-agent/debian/postinst
  rudder-agent/debian/postrm
Labels: qa: Can't merge

#2319 Fixes #17644: some errors when upgrading from 5.0.18nightly to 6.1-nightly on debian9 and 10
  rudder-webapp/debian/preinst
Labels: Ready for merge

#2321 Fixes #17873: SLES12 upgrade error 6.0 to 6.1
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge
