Repository Normation/rudder-packages, pull requests merged in 2020-02, with the labels that each got.

#2198 Fixes #16707: After upgrade from 5.0 to 6.0 on centos7, rudder-slapd is not started
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: qa: Can't merge

#2203 Fixes #16761: rudder-upgrade refers to /opt/rudder/bin/rudder-pkg which doesn't exists in 6.0
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Ready for merge

#2205 Fixes #16766: Missing restorecon in relay postinst for relayd file
  rudder-server-relay/SPECS/rudder-server-relay.spec
Labels: Ready for merge, qa: Can't merge

#2202 Fixes #16745: when upgrding rudder from 5.0 to 6.0, the rudder-pkg restaure pkg cannot restart correctly Jetty, so rudder-upgrade doesn't checkk compatibility, and rudder cannot start
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge, qa: Can't merge

#2207 Fixes #16782: Error on plugins compatibility on upgrade cause the technique to not be updated
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge

#2204 Fixes #16763: same as parent ticket but for postinst
  rudder-webapp/SOURCES/rudder-metrics-reporting
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/preinst
Labels: qa: Can't merge

#2209 Fixes #16792: When upgrading to 6.0.3 the packaging should disable all installed plugins
  rudder-webapp/SOURCES/rudder-upgrade
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge, qa: Can't merge

#2210 Fixes #16796: Avoid moving ncf-api-venv config on SLES
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Ready for merge, qa: Can't merge
