Repository Normation/rudder-packages, pull requests merged in 2021-11, with the labels that each got.

#2538 Fixes #20221: Upgrade dependencies for OpenLDAP & LMDB
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2539 Fixes #20222: upgrade jetty dependency
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2540 Fixes #20224: wrong sha in parent ticket
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2541 Fixes #20232: Git warning about branch name in install logs
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Trigger test

#2543 Fixes #20255: There is no cfengine-systemd patch anymore thus making package build faild
  rudder-agent/SOURCES/Makefile.in
Labels: Ready for merge

#2544 Fixes #20267: error in rudder-agent cron file in packaging
  rudder-agent/SOURCES/Makefile.in
Labels: Trigger test

#2545 Fixes #20288: patch fusioninventory to detect correctly almalinux
  rudder-agent/SOURCES/patches/fusioninventory/16803-correct-sp-on-sles15.patch
  rudder-agent/SOURCES/patches/fusioninventory/20288-correct-detection-for-almalinux.patch
Labels: Trigger test

#2542 Fixes #20244: call the migration script to remove the historaization table at upgrade
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test

#2546 Fixes #20315: Separate openldap cache between nightly and release builds
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge, Trigger test

#2549 Fixes #20330: Clean rudder-packages README
  README.adoc
  README.asciidoc
Labels: Trigger test

#2550 Fixes #20335: Database connection test is broken since the rules table has been removed
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test

#2551 Fixes #20337: System techniques upgrade is broken
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test
