Repository Normation/rudder-packages, pull requests merged in 2021-05, with the labels that each got.

#2480 Fixes #19144: The Generic Method "File copy from Rudder shared Folder" ignores Audit policy mode
  rudder-agent/SOURCES/patches/cfengine/19144-warn-copy-file-directory.patch
Labels: Trigger test, qa: Can't merge

#2481 Fixes #19261: Migration script for rudder.community.port
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test, qa: Can't merge

#2482 Fixes #19289: Remove C client build
  rudder-agent/SOURCES/Makefile.in
Labels: Ready for merge, Trigger test

#2483 Fixes #19291: Rudder 7.0 fails to build when not run from build-task script
  rudder-agent/SOURCES/Makefile.in
  rudder-reports/SOURCES/Makefile
  rudder-server-root/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2484 Fixes #19309: Fusion rudder agent certificate patch fails on windows
  rudder-agent/SOURCES/patches/fusioninventory/14857_use_rudder_certificate.patch
Labels: Trigger test

#2485 Fixes #19315: Fusion inventory cannot read text files that contain BOM
  rudder-agent/SOURCES/Makefile.in
Labels: Trigger test

#2486 Fixes #19325: rpm-build is a build dependency on sles 12
  rudder-agent/SPECS/dependencies
Labels: Trigger test

#2487 Fixes #19332: Add debian 11 support
  rudder-agent/SOURCES/Makefile.in
  rudder-agent/debian/rules
Labels: Trigger test
