Repository Normation/rudder-packages, pull requests merged in 2021-03, with the labels that each got.

#2428 Fixes #18951: Regenerate Makefile for new dependency - 6.1
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2429 Fixes #18956: Parent fails to build
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2430 Fixes #18960: autoconf is not always available
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2431 Fixes #18955: Fatal exception doesn't cause rudder to stop anymore
  rudder-webapp/SOURCES/rudder-jetty.conf
Labels: Trigger test

#2434 Fixes #18963: autoconf is automatically called even if we don't want it
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2435 Fixes #18964: Don't apply systemd patches to non systemd os
  rudder-agent/SOURCES/Makefile
  rudder-agent/SOURCES/patches/cfengine-systemd/18889-systemd-socket.patch
Labels: qa: Can't merge

#2436 Fixes #18966: change autoconf version requirement to 2.64 when building agent, due to missing AM_SUBST_NOTMAKE in 2.63 on sles11
  rudder-agent/SOURCES/Makefile
Labels: Ready for merge, qa: Can't merge

#2437 Fixes #18969: USE_SYSTEMD is not passed to make build on rpm builds
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge, qa: Can't merge

#2438 Fixes #18973: use systemd is not adapted to distro
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge, qa: Can't merge

#2439 Fixes #18975: systemd libs are not installed on builders
  rudder-agent/SPECS/dependencies
  rudder-agent/debian/control
Labels: qa: Can't merge

#2440 Fixes #18974: Package network client on Unix agent
  rudder-agent/SOURCES/Makefile.in
Labels: Trigger test

#2441 Fixes #18986: systemd libs are not installed on builders - ubuntu16 fail to build
  rudder-agent/debian/control
Labels: qa: Can't merge

#2445 Fixes #19002: Rudder 7.0 fails to build
  rudder-agent/SOURCES/configure
  rudder-agent/SOURCES/patches/cfengine-systemd/18889-systemd-socket.patch
  rudder-agent/SOURCES/patches/cfengine/18893-graceful-restart.patch
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge

#2416 Fixes #18891: Upgrade failed from 5.0.20 to 6.1.9 on SLES
  rudder-webapp/SOURCES/rudder-webapp-postinst
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: Trigger test, qa: Can't merge

#2459 Fixes #19027: fail to build on solaris
  rudder-agent/SOURCES/configure
Labels: Ready for merge

#2460 Fixes #19035: Graceful restart should not wait for 10s
  rudder-agent/SOURCES/systemd/rudder-cf-serverd.service
Labels: Trigger test

#2461 Fixes #19044: Upgrade script fails in system technique update (empty commit)
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test

#2462 Fixes #19052: Wrong dependency on augeas
  rudder-agent/debian/rules
Labels: Trigger test

#2463 Fixes #19053: rpmvercmp is missing in 7.0 package
  rudder-agent/SOURCES/Makefile.in
Labels: Trigger test

#2464 Fixes #19054: init script present on systemd systems
  rudder-agent/SOURCES/Makefile.in
Labels: Trigger test

#2465 Fixes #19055: versions file doesn't contain any commit
  rudder-agent/SOURCES/Makefile.in
  rudder-reports/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2466 Fixes #19057: init script present on systemd systems - barent broke debian builds
  rudder-agent/SOURCES/Makefile.in
Labels: Trigger test

#2467 Fixes #19058: init script present on systemd systems - init script sill packaged
  rudder-agent/debian/rules
Labels: Trigger test

#2468 Fixes #19060: Add rudder-api-client as a dependency on rudder server
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/control
Labels: Trigger test

#2469 Fixes #19070: versions file doesn't contain any commit - file format changed
  rudder-agent/SOURCES/Makefile.in
  rudder-reports/SOURCES/Makefile
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2470 Fixes #19090: Update openssl to 1.1.1k
  rudder-agent/SOURCES/Makefile
Labels: Trigger test, qa: Can't merge

#2471 Fixes #19095: Remove 10s delay for restarting cf-serverd
  rudder-agent/SOURCES/systemd/rudder-cf-execd.service
  rudder-agent/SOURCES/systemd/rudder-cf-serverd.service
Labels: Trigger test, qa: Can't merge

#2472 Fixes #19098: Add cross compile option to agent build
  rudder-agent/SOURCES/Makefile.in
  rudder-agent/SOURCES/configure
Labels: Trigger test

#2473 Fixes #19106: Remove unused relay dependencies
  rudder-server-relay/SPECS/dependencies
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
Labels: Trigger test
