Repository Normation/rudder-packages, pull requests merged in 2021-06, with the labels that each got.

#2488 Fixes #19362: Add ci checks for packages
  .gitignore
  Jenkinsfile
  _typos.toml
  build-caching
  docopt.py
  qa-test
  rudder-agent/SOURCES/debug-script/tests/rudder_defaultpassword
  rudder-agent/SOURCES/debug-script/tests/rudder_packages_agent
  rudder-agent/SOURCES/openssl.cnf
  rudder-agent/SOURCES/patches/cfengine/17335-remove-performance-writes.patch
  rudder-agent/SOURCES/rudder-agent-postinst
  rudder-webapp/SOURCES/patches/jetty/jetty-init-sizecheck.patch
  rudder-webapp/SOURCES/rudder-apache-webapp-common.conf
  rudder-webapp/SOURCES/rudder-init
  rudder-webapp/SOURCES/rudder-jetty-base/start.ini
  rudder-webapp/SOURCES/rudder-node-to-relay
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test, qa: Can't merge

#2489 Fixes #19365: Add ci checks for packages - 6.2
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test, qa: Can't merge

#2490 Fixes #19366: Add ci checks for packages - master
  rudder-agent/SPECS/rudder-agent.spec
Labels: Trigger test

#2491 Fixes #19373: Remove build of tomlc99
  rudder-agent/SOURCES/Makefile.in
  rudder-agent/SOURCES/configure
  rudder-webapp/SOURCES/Makefile
Labels: Trigger test

#2492 Fixes #19387: rsync is a build dependency
  rudder-agent/SPECS/rudder-agent.spec
  rudder-webapp/SPECS/dependencies
Labels: Trigger test

#2493 Fixes #19391: Add debian 11 build flags to 6.2
  rudder-agent/debian/rules
Labels: Trigger test, qa: Can't merge

#2494 Fixes #19393: webapp package depends on rust
  rudder-webapp/SPECS/dependencies
Labels: Trigger test

#2495 Fixes #19406: Broken agent postinst script
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: Trigger test

#2496 Fixes #19429: rudder-agent-postinst fails in 7.0 while closing fd
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: Ready for merge, Trigger test

#2498 Fixes #19469: Rename rudder language and extension - packaging
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Trigger test

#2499 Fixes #19483: CFEngine 3.18 LTS on 7.0
  rudder-agent/SOURCES/.gitignore
  rudder-agent/SOURCES/Makefile.in
  rudder-agent/SOURCES/patches/cfengine-systemd/18889-systemd-socket.patch
  rudder-agent/SOURCES/patches/cfengine-systemd/18893-graceful-restart.patch
  rudder-agent/SOURCES/patches/cfengine/18286-add-copyfrom-restrict-keys-keyword.patch
  rudder-agent/SOURCES/patches/cfengine/18732-fix-on-background-command-execution-on-agent.patch
  rudder-agent/SOURCES/patches/cfengine/18893-graceful-restart.patch
  rudder-agent/SOURCES/patches/cfengine/19144-warn-copy-file-directory.patch
Labels: Trigger test
