Repository Normation/rudder-packages, pull requests merged in 2021-12, with the labels that each got.

#2552 Fixes #20356: When upgrading from 6.2 -> 7.0 on centos8, old system technique are still present, and break policy generation
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test

#2554 Fixes #19163: Do not display the jetty version number
  rudder-webapp/SOURCES/rudder-jetty-base/start.ini
Labels: Trigger test

#2553 Fixes #20376: rudder-webapp 6.2 on debian11 generate a dbgsym package
  rudder-webapp/debian/rules
Labels: qa: Can't merge, Trigger test

#2557 Fixes #20450: Separate openldap cache between nightly and release builds - 6.2
  rudder-webapp/SOURCES/Makefile
Labels: Ready for merge, Trigger test

#2555 Fixes #20428: Update openssl to 1.1.1m
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2558 Fixes #20475: Wrong version/hash for openssl
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2559 Fixes #20268: /etc/cron.d/rudder-agent is a conffile
  rudder-agent/debian/postrm
  rudder-agent/debian/rules
Labels: Trigger test

#2560 /etc/cron.d/rudder-agent is a conffile in rpm too
  rudder-agent/SPECS/rudder-agent.spec
Labels: Trigger test
