Repository Normation/rudder-packages, pull requests merged in 2022-05, with the labels that each got.

#2594 Fixes #21084: Create a new rudder-server package
  rudder-server/Makefile
  rudder-server/SOURCES/Makefile
  rudder-server/SOURCES/ca-bundle.crt
  rudder-server/SOURCES/mvn-like
  rudder-server/SOURCES/patches/jetty/jetty-console-capture-restore-log-filename.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-prevent-false-failed-starts.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-redirect-stderrout.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-sizecheck.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-sles.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-softokn-version-check.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-stop-fix.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-stop-forcestop.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-ulimit.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-umask.patch
  rudder-server/SOURCES/patches/openldap/0005-not-indexed-messages-to-trace-level.patch
  rudder-server/SOURCES/patches/openldap/0006-not-indexed-messages-to-trace-level-mdb.patch
  rudder-server/SOURCES/rsyslog/rudder-slapd.conf
  rudder-server/SOURCES/rudder-apache-webapp-common.conf
  rudder-server/SOURCES/rudder-apache-webapp-nossl.conf
  rudder-server/SOURCES/rudder-apache-webapp-ssl.conf
  rudder-server/SOURCES/rudder-fix-repository-permissions
  rudder-server/SOURCES/rudder-init
  rudder-server/SOURCES/rudder-jetty-base/etc/console-capture.xml
  rudder-server/SOURCES/rudder-jetty-base/resources/jetty-logging.properties
  rudder-server/SOURCES/rudder-jetty-base/start.ini
  rudder-server/SOURCES/rudder-jetty.conf
  rudder-server/SOURCES/rudder-jetty.default
  rudder-server/SOURCES/rudder-jetty.service
  rudder-server/SOURCES/rudder-metrics-reporting
  rudder-server/SOURCES/rudder-node-to-relay
  rudder-server/SOURCES/rudder-passwords.conf
  rudder-server/SOURCES/rudder-reload-cf-serverd
  rudder-server/SOURCES/rudder-reports-postinst
  rudder-server/SOURCES/rudder-server-root-postinst
  rudder-server/SOURCES/rudder-server.service
  rudder-server/SOURCES/rudder-slapd-hardening
  rudder-server/SOURCES/rudder-slapd.service
  rudder-server/SOURCES/rudder-upgrade
  rudder-server/SOURCES/rudder-webapp
  rudder-server/SOURCES/rudder-webapp-apache
  rudder-server/SOURCES/rudder-webapp-postinst
  rudder-server/SOURCES/rudder-webapp.fc
  rudder-server/SOURCES/rudder-webapp.te
  rudder-server/SOURCES/rudder.xml
  rudder-server/SOURCES/rudder_synchronize.py
  rudder-server/SOURCES/slapd.conf
  rudder-server/SPECS/dependencies
  rudder-server/SPECS/rudder-server.spec
  rudder-server/debian/changelog
  rudder-server/debian/compat
  rudder-server/debian/conffiles
  rudder-server/debian/control
  rudder-server/debian/copyright
  rudder-server/debian/postinst
  rudder-server/debian/postrm
  rudder-server/debian/preinst
  rudder-server/debian/prerm
  rudder-server/debian/rules
Labels: Trigger test

#2596 Fixes #21097: Cleanup package build
  rudder-agent/debian/control
  rudder-api-client/debian/control
  rudder-relay/debian/compat
  rudder-relay/debian/control
  rudder-relay/debian/postrm
  rudder-relay/debian/rules
  rudder-server-relay/TODO
  rudder-server-relay/debian/control
  rudder-server-root/TODO
  rudder-server-root/debian/control
  rudder-server/SOURCES/Makefile
  rudder-server/SOURCES/rudder-upgrade
  rudder-server/SPECS/rudder-server.spec
  rudder-server/debian/control
Labels: Trigger test

#2598 Fixes #21098: Merge rudder-server postinst
  rudder-server/SOURCES/Makefile
  rudder-server/SOURCES/rudder-init
  rudder-server/SOURCES/rudder-reports-postinst
  rudder-server/SOURCES/rudder-server-postinst
  rudder-server/SOURCES/rudder-server-root-postinst
  rudder-server/SOURCES/rudder-upgrade
  rudder-server/SOURCES/rudder-webapp-postinst
  rudder-server/SPECS/rudder-server.spec
  rudder-server/debian/postinst
Labels: Trigger test

#2601 Fixes #21116: Cannot build 7. anymore
  rudder-server/SOURCES/Makefile
Labels: Trigger test

#2602 Fixes #21118: Can't build 7.2 on rhel8
  rudder-relay/SPECS/rudder-relay.spec
Labels: Trigger test

#2603 Fixes #21120: rudder-relay postinst fails to restart apache
  rudder-relay/debian/postinst
  rudder-server/debian/control
  rudder-server/debian/postinst
Labels: Trigger test

#2604 Fixes #21128: wrong dependency on rudder-server for rpm
  rudder-relay/SPECS/rudder-relay.spec
  rudder-server/SOURCES/rudder-server-postinst
  rudder-server/SPECS/rudder-server.spec
Labels: Ready for merge, Trigger test

#2599 Fixes #21109: Make java 11 the minimum version for rudder 7.2
  rudder-server/SOURCES/rudder-jetty.conf
  rudder-server/SPECS/rudder-server.spec
Labels: Ready for merge, Trigger test

#2605 Fixes #21141: Update C/C++ dependencies for 7.2
  rudder-agent/SOURCES/17336-remove-lock-db-backup.patch
  rudder-agent/SOURCES/Makefile.in
  rudder-server/SOURCES/Makefile
  rudder-server/SOURCES/patches/openldap/0005-not-indexed-messages-to-trace-level.patch
  rudder-server/SOURCES/patches/openldap/0006-not-indexed-messages-to-trace-level-mdb.patch
Labels: Ready for merge, Trigger test

#2607 Fixes #21137: Upgrade Jetty version for Rudder 7.2
  rudder-server/SOURCES/Makefile
  rudder-server/SOURCES/patches/jetty/jetty-console-capture-restore-log-filename.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-prevent-false-failed-starts.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-sizecheck.patch
  rudder-server/SOURCES/patches/jetty/jetty-init-umask.patch
  rudder-server/SOURCES/rudder-jetty-base/etc/console-capture.xml
Labels: Ready for merge, Trigger test

#2593 Fixes #21067: Add windows support to the inventory software update section
  rudder-agent/SOURCES/patches/fusioninventory/21067-windows-updates.patch
Labels: Ready for merge, Trigger test

#2609 Fixes #21158: fusion inventory patch is not complete
  rudder-agent/SOURCES/patches/fusioninventory/21067-windows-updates.patch
Labels: Ready for merge

#2610 Fixes #21164: Windows support for the software update patch in fusion does not respect the expected webapp format
  rudder-agent/SOURCES/patches/fusioninventory/21067-windows-updates.patch
Labels: Ready for merge, Trigger test

#2608 Fixes #21086: Create a package for people having an external DB
  rudder-external-db/Makefile
  rudder-external-db/SOURCES/Makefile
  rudder-external-db/SOURCES/external-db.conf
  rudder-external-db/SOURCES/rudder-external-db-postinst
  rudder-external-db/SPECS/rudder-external-db.spec
  rudder-external-db/debian/changelog
  rudder-external-db/debian/compat
  rudder-external-db/debian/control
  rudder-external-db/debian/copyright
  rudder-external-db/debian/rules
  rudder-server/SOURCES/rudder-server-postinst
  rudder-server/SPECS/rudder-server.spec
  rudder-server/debian/control
Labels: Ready for merge, Trigger test

#2606 Fixes #21151: Make rudder-jetty.conf and default rudder-jetty compatible with JVM 11 and 17
  rudder-server/SOURCES/rudder-jetty.conf
  rudder-server/SOURCES/rudder-jetty.default
  rudder-server/debian/conffiles
Labels: Ready for merge, Trigger test

#2611 Fixes #20263: Missing SELinux rules for httpd on RockyLinux
  rudder-server-relay/SPECS/rudder-server-relay.spec
Labels: Ready for merge, qa: Can't merge, Trigger test
