Repository Normation/rudder-packages, pull requests merged in 2022-01, with the labels that each got.

#2562 Fixes #20522: rudder-agent-postinst doesn't close file descriptors anymore
  rudder-agent/SOURCES/rudder-agent-postinst
Labels: qa: Can't merge, Trigger test

#2561 Fixes #20521: Improve agen-side messages when download is refused
  rudder-agent/SOURCES/.gitignore
  rudder-agent/SOURCES/patches/cfengine/20521-log-refused.patch
Labels: qa: Can't merge, Trigger test

#2563 Fixes #20524: Improve agent-side messages when download is refused - 7.0
  rudder-agent/SOURCES/patches/cfengine/20521-log-refused.patch
Labels: Trigger test

#2564 Fixes #20537: webapp installation produces a warning about initial branch name
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: Trigger test

#2565 Fixes #20539: webapp preinst should run rudder agent check
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/preinst
Labels: Trigger test

#2566 Fixes #20570: webapp preinst should run rudder agent check - but with only certificate checks
  rudder-webapp/SPECS/rudder-webapp.spec
  rudder-webapp/debian/preinst
Labels: Trigger test

#2567 Fixes #20578: Remove the old technique editor
  rudder-webapp/SOURCES/Makefile
  rudder-webapp/SOURCES/rudder-apache-webapp-ssl.conf
  rudder-webapp/SOURCES/rudder-upgrade
Labels: Trigger test

#2568 Fixes #20645: rudder_synchronize fails to import technique
  rudder-webapp/SOURCES/rudder_synchronize.py
Labels: Ready for merge, Trigger test

#2548 Fixes #20329: Update to CFEngine 3.18.1
  rudder-agent/SOURCES/Makefile.in
  rudder-agent/SOURCES/patches/cfengine/19830-empty-file-backup.patch
Labels: Trigger test

#2569 Fixes #20670: Missing fusion patches for windows agent
  rudder-agent/SOURCES/patches/fusioninventory/20670-windows-inventory-hooks.patch
Labels: Trigger test
