Repository Normation/rudder-packages, pull requests merged in 2022-07, with the labels that each got.

#2634 Fixes #21357: Add rhel9 support to packages
  rudder-agent/SPECS/dependencies
  rudder-agent/SPECS/rudder-agent.spec
  rudder-api-client/SPECS/dependencies
  rudder-api-client/SPECS/rudder-api-client.spec
  rudder-relay/SPECS/dependencies
  rudder-server/SPECS/dependencies
  rudder-server/SPECS/rudder-server.spec
Labels: Trigger test

#2635 Fixes #21359: Add rhel9 support to packages - openssl 3 only
  rudder-agent/SPECS/rudder-agent.spec
Labels: Ready for merge, Trigger test

#2637 Fixes #21361: unescaped percent in specfile
  rudder-agent/SPECS/rudder-agent.spec
  rudder-relay/SPECS/rudder-relay.spec
  rudder-server/SPECS/rudder-server.spec
Labels: Trigger test

#2636 Fixes #21360: Update embedded openssl to 1.1.1q
  rudder-agent/SOURCES/Makefile
Labels: qa: Can't merge

#2638 Fixes #21363: unescaped percent in specfile - too many %
  rudder-server/SPECS/rudder-server.spec
Labels: Trigger test

#2640 Fixes #21381: yum installs external-db instead of postgresql by default - still the same
  rudder-server/SPECS/rudder-server.spec
Labels: Ready for merge, Trigger test

#2641 Fixes #21382: yum installs external-db instead of postgresql by default - bis
  rudder-server/SPECS/rudder-server.spec
Labels: Trigger test
