Repository Normation/rudder-packages, pull requests merged in 2022-04, with the labels that each got.

#2585 Fixes #20974: rudder-webapp requires rsync to build for RHEL
  rudder-webapp/SPECS/dependencies
Labels: qa: Can't merge

#2588 Fixes #21036: ubuntu22 build options are missing
  rudder-agent/debian/rules
Labels: Ready for merge, Trigger test

#2589 Fixes #21040: Embed openssl on ubuntu 22.04
  rudder-agent/debian/rules
Labels: Trigger test

#2591 Fixes #21041: Specify compression tool in debian packages
  rudder-agent/debian/rules
  rudder-api-client/debian/rules
  rudder-reports/debian/rules
  rudder-server-relay/debian/rules
  rudder-server-root/debian/rules
  rudder-webapp/debian/rules
Labels: Trigger test
