Repository Normation/rudder-packages, pull requests merged in 2022-06, with the labels that each got.

#2612 Fixes #21211: parsing of system fusioninventory is invalid
  rudder-agent/SOURCES/run-inventory
Labels: Trigger test

#2613 Fixes #21244: Add an index on softwareId to have queries on software much faster
  rudder-server/SOURCES/rudder-upgrade
  rudder-server/SOURCES/slapd.conf
Labels: Trigger test

#2614 Fixes #21246: Add an index on nodeId to have queries on nodes much faster, as well as software related action faster
  rudder-server/SOURCES/rudder-upgrade
  rudder-server/SOURCES/slapd.conf
Labels: Trigger test

#2618 Fixes #21276: Broken build on 7.2 for debian10 - server
  rudder-server/debian/rules
Labels: Ready for merge

#2620 Fixes #21219: relayd can't connect to postgresql on Ubuntu 22.04 server
  rudder-server-relay/debian/rules
Labels: Ready for merge, qa: Can't merge

#2622 Fixes #21300: Use new rudderc binary
  rudder-server/SOURCES/Makefile
Labels: Ready for merge

#2623 Fixes #21301: Java does not default to 11 even if it is installed
  rudder-server/SOURCES/rudder-server-postinst
Labels: Ready for merge, Trigger test

#2625 Fixes #21325: rudder-relay cannot take over rudder-server-relay because of conffiles
  rudder-relay/debian/preinst
Labels: Trigger test

#2627 Fixes #21329: conffiles must be restored after a divert
  rudder-relay/debian/postinst
Labels: Ready for merge, Trigger test

#2626 Fixes #21328: groff is necessary to build rudder server
  rudder-server/SPECS/rudder-server.spec
Labels: Ready for merge, Trigger test

#2631 Fixes #21339: external-db doesn't build for rpm - build fail
  rudder-external-db/SPECS/rudder-external-db.spec
Labels: Trigger test

#2632 Fixes #21340: external-db doesn't build for rpm - wrong password file
  rudder-server/SOURCES/rudder-server-postinst
Labels: Trigger test

#2633 Fixes #21351: external db should set rudder.postgresql.local to false
  rudder-external-db/SOURCES/external-db.conf
  rudder-server/SOURCES/rudder-server-postinst
Labels: Trigger test
