Repository Normation/rudder-packages, pull requests merged in 2023-09, with the labels that each got.

#2806 Fixes #23391: Revert libxml upgrade
  rudder-agent/SOURCES/Makefile.in
Labels: Ready for merge

#2807 Fixes #23388: Server install fails with postgresql encoding error
  rudder-external-db/SOURCES/external-db.conf
  rudder-external-db/SOURCES/rudder-external-db-postinst
  rudder-server/SOURCES/rudder-server-postinst
Labels: qa: Can't merge

#2808 Fixes #23395: Error in create database syntaxe: template AFTER owner
  rudder-external-db/SOURCES/external-db.conf
  rudder-external-db/SOURCES/rudder-external-db-postinst
  rudder-server/SOURCES/rudder-server-postinst
Labels: qa: Can't merge

#2809 Fixes #23410: Bump to openssl 1.1.1w
  rudder-agent/SOURCES/Makefile.in
Labels: Ready for merge, qa: Can't merge

#2810 Fixes #23436: Rudder 8.0 cannot be installed on sles15sp4 due to dependency error
  rudder-server/SPECS/rudder-server.spec
Labels: Ready for merge

#2811 Fixes #23437: Function cache can return incorrect results
  rudder-agent/SOURCES/patches/cfengine/23437-function-comparison.patch
  rudder-agent/SOURCES/patches/cfengine/23437-function-name.patch
Labels: Ready for merge

#2812 Fixes #23449: Dependency on rudder-api-client should be versioned
  rudder-server/SPECS/rudder-server.spec
  rudder-server/debian/control
  rudder-server/debian/rules
Labels: Ready for merge, qa: Can't merge

#2813 Fixes #23452: Update OpenSSL to 3.1.3
  rudder-agent/SOURCES/Makefile.in
Labels: Ready for merge

#2814 Fixes #22930: tar is not an explicit dependency of the Rudder server
  rudder-server/SPECS/rudder-server.spec
  rudder-server/debian/control
Labels: qa: Can't merge
