Repository Normation/rudder-packages, pull requests merged in 2023-01, with the labels that each got.

#2692 Fixes #22251: Improve CI Notifications of rudder-packages
  Jenkinsfile
Labels: Ready for merge

#2694 Fixes #22257: inventory are rejected due to missing dependencies on the server
  rudder-server-relay/SPECS/rudder-server-relay.spec
Labels: qa: Can't merge

#2698 Fixes #22267: on rhel postinst uses yum creating a deadlock
  rudder-webapp/SOURCES/rudder-webapp-postinst
Labels: qa: Can't merge

#2700 Fixes #22310: Add git as Rust build dependency
  rudder-server-relay/SPECS/dependencies
  rudder-server-relay/SPECS/rudder-server-relay.spec
  rudder-server-relay/debian/control
  rudder-webapp/SPECS/dependencies
  rudder-webapp/SPECS/rudder-webapp.spec
Labels: Ready for merge, qa: Can't merge
