Repository Normation/rudder-packages, pull requests merged in 2023-05, with the labels that each got.

#2729 Fixes #20937: Postgresql is not created with the UTF8 encoding
  rudder-external-db/SOURCES/external-db.conf
  rudder-external-db/SOURCES/rudder-external-db-postinst
  rudder-server/SOURCES/rudder-server-postinst
Labels: Ready for merge

#2727 Fixes #15636: Errors with Rudder agent on unprivileged containers (LXC)
  rudder-agent/SOURCES/patches/cfengine/15636-ignore-symlink-check-on-lxc.patch
Labels: Ready for merge

#2742 Fixes #22780: install fails on redhat, because postgres is not initialized
  rudder-server/SOURCES/rudder-server-postinst
Labels: Ready for merge

#2744 Fixes #22782: git is a build dependency for rudder-server package
  rudder-server/SPECS/dependencies
Labels: Ready for merge, qa: Can't merge

#2737 Fixes #22749: resources sent to the browser are not compressed when using a custom cetificate
  rudder-server/SOURCES/rudder-apache-webapp-ssl.conf
Labels: qa: Can't merge

#2745 Fixes #22786: git is a build dependency for rudder-server package - sles git package name error
  rudder-server/SPECS/dependencies
Labels: qa: Can't merge
