Repository Normation/rudder-packages, pull requests merged in 2024-03, with the labels that each got.

#2857 Fixes #24320: rudder-sign fails on some machines with openssl 3
  rudder-agent/SOURCES/rudder-sign
Labels: Ready for merge

#2859 Fixes #24359: Typo in rudder-sign openssl 3 signing regex
  rudder-agent/SOURCES/rudder-sign
Labels: Ready for merge

#2860 Fixes #24449: Move plugins postupgrade after webapp restart
  rudder-server/SOURCES/rudder-server-postinst
Labels: Ready for merge, qa: Can't merge

#2861 Fixes #24569: Adapt rudder-agent packaging for Ubuntu 24.04
  rudder-agent/debian/rules
Labels: qa: Can't merge
