Repository Normation/rudder-packages, pull requests merged in 2025-06, with the labels that each got.

#2997 Fixes #27055: Remove cfengine-community/bin
  rudder-agent/SOURCES/rudder-agent-postinst
  rudder-agent/SPECS/rudder-agent.spec
  rudder-agent/debian/dirs
Labels: Ready for merge

#3000 Fixes #27068: Typo in parent issue: --fstack-clash-protection
  rudder-agent/SOURCES/configure
Labels: Ready for merge

#3002 Fixes #27072: Update curl & openssl
  rudder-agent/SOURCES/Makefile.in
  rudder-external-db/SOURCES/external-db.conf
  rudder-external-db/SOURCES/rudder-external-db-postinst
Labels: Ready for merge

#3004 Fixes #27082: Define the "suse" class on SLED systems
  rudder-agent/SOURCES/patches/cfengine/27082-define_the_suse_class_on_sled_systems.patch
Labels: Ready for merge, qa: Can't merge

#2974 Fixes #26654: libpq may be missing on rudder-relay on alma8
  rudder-relay/SPECS/rudder-relay.spec
Labels: qa: Can't merge
